databases:
  - name: dulceria_CRUD
    plan: free
    databaseName: dulceriadb
    user: dulceriadb

services:
  - type: web
    plan: free
    name: dulceria
    runtime: python
    buildCommand: "cd app && chmod +x build.sh && ./build.sh"
    startCommand: "cd app && gunicorn app.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      # Configuración esencial de Django
      - key: DATABASE_URL
        fromDatabase:
          name: dulceria_CRUD
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "app.settings.production"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      
      # Variables del superusuario
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin_stephanie"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "stephanie@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      
      # Optimización de rendimiento
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONBUFFERED
        value: 1
      - key: DISABLE_COLLECTSTATIC
        value: 0
      
      # Configuración adicional recomendada
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: DEBUG
        value: "False"