databases:
  - name: dulceria_CRUD
    plan: free
    databaseName: dulceriadb
    user: dulceriadb

services:
  - type: web
    plan: free
    name: dulceria
    runtime: python
    buildCommand: './app/build.sh'
    startCommand: 'python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dulceria_CRUD
          property: connectionString
      - key: DJANGO_ENVIRONMENT
        value: production
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4