databases:
  - name: dulceria_CRUD
    plan: free
    databaseName: dulceriadb
    user: dulceriadb

services:
  - type: web
    plan: free
    name: dulceria
    runtime: python
    buildCommand: "cd app && ./build.sh"
    startCommand: "cd app && gunicorn app.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dulceria_CRUD
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "app.settings.production"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: 4